server:
  port: 8012
spring:
  application:
    name: spring-cloud-user
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka