server:
  port: 9764
spring:
  application:
    name: spring-cloud-ribbon
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka